name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
    - uses: actions/setup-python@0f07f7f756721ebd886c2462646a35f78a8bc4de # v1.2.4
      with:
        python-version: '3.7'
    - name: Build wheels
      run: ./scripts/build.sh
    - name: Install twine
      run: |
        pip install twine
    # The step below publishes to testpypi in order to catch any issues
    # with the package configuration that would cause a failure to upload
    # to pypi. One example of such a failure is if a classifier is
    # rejected by pypi (e.g "3 - Beta"). This would cause a failure during the
    # middle of the package upload causing the action to fail, and certain packages
    # might have already been updated, this would be bad.
    - name: Publish to TestPyPI
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_AUTOMATIC_RELEASE_TOKEN }}
      run: |
        twine upload --repository testpypi --skip-existing --verbose dist/*
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.PYPI_AUTOMATIC_RELEASE_TOKEN }}
      run: |
        twine upload --skip-existing --verbose dist/*
